### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by 3willows** [simonholmes/mongoose-default-connection#2]
http://theholmesoffice.com/mongoose-connection-best-practice/ now links to a page irrelevant to mongoose default connection.

**Comment by 3willows** [comment]
Web archive link here: https://web.archive.org/web/20140330182958/http://theholmesoffice.com/mongoose-connection-best-practice/

**Comment by simonholmes** [comment]
Added to the readme. Thanks @3willows
